### ISSUE TITLE
Error during VM Creation

### ISSUE THREAD

**Issue by nlamirault** [frapposelli/vagrant-vcloud#110]
I try the setup "Protected vApp Network with Organization VDC Edge Gateway". After creating first VM, i've got an error : 

``` bash
$ VAGRANT_LOG=info bundle exec vagrant up web-vm --provider=vcloud
[...]
==> web-vm: Building vApp...
 INFO machine: New vApp ID: "133b3132-b951-4c06-a29b-05a682cf60e1"
 INFO interface: success: vApp stratus successfully created.
 INFO interface: success: ==> web-vm: vApp stratus successfully created.
==> web-vm: vApp stratus successfully created.
 INFO machine: New machine ID: "1a9fb293-d1d5-46f4-9a93-36ef68e42129"
 INFO build_vapp: Setting Guest Customization on ID: [web-vm] of vApp [stratus]
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x007f6a00a1f060>
 INFO warden: Calling IN action: #<VagrantPlugins::VCloud::Action::PowerOn:0x007f6a00a1f038>
 INFO interface: info: Setting VM hardware...
 INFO interface: info: ==> web-vm: Setting VM hardware...
==> web-vm: Setting VM hardware...
 INFO interface: info: Powering on VM...
 INFO interface: info: ==> web-vm: Powering on VM...
==> web-vm: Powering on VM...
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Call:0x007f6a00a50368>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000002a3cb98>
 INFO warden: Calling IN action: #<VagrantPlugins::VCloud::Action::IsCreated:0x00000002a8a078>
 INFO is_created: vApp has been created and ID is: [133b3132-b951-4c06-a29b-05a682cf60e1]
 INFO is_created: VM has been added to vApp and ID is: [1a9fb293-d1d5-46f4-9a93-36ef68e42129]
 INFO warden: Calling OUT action: #<VagrantPlugins::VCloud::Action::IsCreated:0x00000002a8a078>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Warden:0x00000003445950>
 INFO warden: Calling IN action: #<Proc:0x000000035fd158@/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #<VagrantPlugins::VCloud::Action::HandleNATPortCollisions:0x000000034458b0>
 INFO handle_port_collisions: Detecting any forwarded port collisions...
ERROR warden: Error occurred: Unattended code received 404
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Unattended code received 404
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Unattended code received 404
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x007f6a00a50368>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Unattended code received 404
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Unattended code received 404
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000003484b50>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x000000035a3bf8>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Unattended code received 404
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Unattended code received 404
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-d3a1ba3a6b24adb864c959411215a5d7
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x000000040f6e38>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::VCloud::Errors::UnattendedCodeError: Unattended code received 404>
ERROR vagrant: Unattended code received 404
ERROR vagrant: /home/nlamirault/OAB/Outils/stratus/vagrant-vcloud/lib/vagrant-vcloud/driver/base.rb:341:in `send_request'
/home/nlamirault/OAB/Outils/stratus/vagrant-vcloud/lib/vagrant-vcloud/driver/version_5_1.rb:1231:in `get_edge_gateway_rules'
/home/nlamirault/OAB/Outils/stratus/vagrant-vcloud/lib/vagrant-vcloud/action/handle_nat_port_collisions.rb:53:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/builder.rb:116:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/runner.rb:66:in `block in run'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/util/busy.rb:19:in `busy'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/runner.rb:66:in `run'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/builtin/call.rb:53:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/OAB/Outils/stratus/vagrant-vcloud/lib/vagrant-vcloud/action/power_on.rb:35:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/OAB/Outils/stratus/vagrant-vcloud/lib/vagrant-vcloud/action/build_vapp.rb:221:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/builder.rb:116:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/runner.rb:66:in `block in run'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/util/busy.rb:19:in `busy'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/runner.rb:66:in `run'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/builtin/call.rb:53:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/OAB/Outils/stratus/vagrant-vcloud/lib/vagrant-vcloud/action/inventory_check.rb:15:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/OAB/Outils/stratus/vagrant-vcloud/lib/vagrant-vcloud/action/connect_vcloud.rb:50:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/builder.rb:116:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/runner.rb:66:in `block in run'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/util/busy.rb:19:in `busy'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/runner.rb:66:in `run'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/builtin/call.rb:53:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/warden.rb:34:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/builder.rb:116:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/runner.rb:66:in `block in run'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/util/busy.rb:19:in `busy'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/action/runner.rb:66:in `run'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/machine.rb:214:in `action_raw'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/machine.rb:191:in `block in action'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/environment.rb:516:in `lock'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/machine.rb:178:in `call'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/machine.rb:178:in `action'
/home/nlamirault/.bundler/ruby/2.1.0/vagrant-4cd767afcc1c/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: Unattended code received 404
Unattended code received 404
 INFO interface: Machine: error-exit ["VagrantPlugins::VCloud::Errors::UnattendedCodeError", "Unattended code received 404"]

```

But VM seems online in the vCloud Director UI. Any idea ?

**Comment by frapposelli** [comment]
You're getting a 404 when trying to fetch the Edge Gateway rules, please run the command again with `VAGRANT_LOG=DEBUG` and post it (make sure to hide information you don't want to share).
