### ISSUE TITLE
404 when adding a node

### ISSUE THREAD

**Issue by jeffcasavant** [frapposelli/vagrant-vcloud#119]
I get a 404 with my configuration.  I'm attempting to deploy two nodes, one web and one db.  The deploy succeeds up to the point when the first node boots.  After the first node boots, vagrant crashes with a 404.

```
ERROR vagrant: Unattended code received 404                                                                                                                                                                                                   
ERROR vagrant: /home/jeff/.vagrant.d/gems/gems/vagrant-vcloud-0.4.4/lib/vagrant-vcloud/driver/base.rb:344:in `send_request'                                                                                                                   
/home/jeff/.vagrant.d/gems/gems/vagrant-vcloud-0.4.4/lib/vagrant-vcloud/driver/version_5_1.rb:1231:in `get_edge_gateway_rules' 
```

My [vagrantfile](https://gist.github.com/jeffcasavant/5601cf9b342f47f8b391) and my [logfile](https://gist.github.com/jeffcasavant/f5cbfacfdfead1c2bef3) are available if they would help.

**Comment by jeffcasavant** [comment]
Did some digging and it appears that the CSS selector on lib/vagrant-vcloud/driver/version5_1.rb line 1130 does not work with my setup. I have no edge gateways at all, so:

* no records are returned by the query for a list of edge gateways
* find_edge_gateway_id(...) parses the empty list and returns an empty string to  get_edge_gateway_rules(...)
* get_edge_gateway_rules(...) queries the URL "api/admin/edgeGateway/{gatewayID}" (gatewayID being the empty string)
* finally, the URL api/admin/edgeGateway is not defined by the vCloud API, so I get a 404

I gather that I will need an edge gateway as a workaround for right now.

**Comment by jeffcasavant** [comment]
Suspect I have the same issue as #110
