### ISSUE TITLE
Support Vagrant 1.8.1

### ISSUE THREAD

**Issue by StefanScherer** [frapposelli/vagrant-vcloud#122]
We should update the dependencies so that this plugin works with Vagrant 1.8.1. I've created a clean Windows box with Vagrant 1.8.1 and installed this plugin. On `vagrant up` I get this error:

```
C:\Users\vagrant\vcloud-scenarios\windows\vappnetwork\windows_2012_r2 [change_sid ≡]> vagrant up tst
C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:29:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/Users/vagrant/.vagrant.d/gems/gems/vagrant-vcloud-0.4.5.204/lib/vagrant-vcloud/driver/meta.rb:20:in `require'
        from C:/Users/vagrant/.vagrant.d/gems/gems/vagrant-vcloud-0.4.5.204/lib/vagrant-vcloud/driver/meta.rb:20:in `<top (required)>'
        from C:/Users/vagrant/.vagrant.d/gems/gems/vagrant-vcloud-0.4.5.204/lib/vagrant-vcloud/action/connect_vcloud.rb:23:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
```

The plugin installs httpclient 2.3.4.1, but Vagrant itself has 2.7.0.1 in its embedded folder.

**Comment by StefanScherer** [comment]
The problem is in Vagrant itself. Vagrant 1.8.1 has Ruby 2.2.3 embedded and nokogiri 1.6.3.1 does not have support for Ruby 2.2, the folder is missing and therefore the gem does not in this constellation.
Found https://github.com/mitchellh/vagrant/issues/6766.

**Comment by StefanScherer** [comment]
A PR https://github.com/mitchellh/vagrant/pull/6848 is already on its way...
