### ISSUE TITLE
Fails to install on Vagrant v1.9.3

### ISSUE THREAD

**Issue by dandunckelman** [frapposelli/vagrant-vcloud#140]
# Summary
When trying to install this plugin on Vagrant 1.9.3, it fails.

# Environment Info
- OS:  Ubuntu 16.04
- Vagrant:  1.9.3 installed via deb file

# Error message
```
$ vagrant plugin install vagrant-vcloud
Installing the 'vagrant-vcloud' plugin. This can take a few minutes...                                                                                                                 
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate httpclient-2.3.4.1, already activated httpclient-2.8.3 (Gem::LoadError)
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'                                                                                         
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:357:in `block in activate_solution'                                                                  
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:354:in `each'                                                                                        
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:354:in `activate_solution'                                                                           
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:279:in `internal_install'                                                                            
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:104:in `install'                                                                                     
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'                                                               
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/manager.rb:72:in `call'                                                                                  
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/manager.rb:72:in `install_plugin'                                                                        
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/action/install_gem.rb:29:in `call'                                                                  
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'                                                                                   
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builder.rb:116:in `call'                                                                                 
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `block in run'                                                                           
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/busy.rb:19:in `busy'                                                                                       
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `run'                                                                                    
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/base.rb:14:in `action'                                                                      
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/install.rb:32:in `block in execute'                                                         
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/install.rb:31:in `each'                                                                     
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/install.rb:31:in `execute'                                                                  
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/root.rb:66:in `execute'                                                                     
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/cli.rb:42:in `execute'                                                                                          
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:308:in `cli'                                                                                     
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/bin/vagrant:127:in `<main>'                                                                                                 
```

# Possible Solutions
- Update the httpclient gem requirement
- Others?

**Comment by dandunckelman** [comment]
Resolved by #137
